const routes = {
  Home: "/",
  FilmSchedule: "/lich-chieu-theo-phim",
  TheaterSchedule: "/lich-chieu",
  TheaterSystem: "/he-thong-rap",
  Promotion: "/khuyen-mai",
  Event: "/su-kien",
  Advertise: "/dich-vu-quang-cao",
  Recruitment: "/tuyen-dung",
  Information: "/ve-chung-toi",
  Account: "/tai-khoan",
  Rules: "/dieu-khoan",
  MemberRule: "/quy-dinh-thanh-vien",
  TicketInstruction: "/quy-dinh-va-hinh-thuc-thanh-toan",
  Policy: "/quy-dinh-va-chinh-sach-chung",
  UserSecurity:
    "/dieu-khoan/chinh-sach-bao-ve-thong-tin-ca-nhan-cua-nguoi-tieu-dung",
  Register: "/dang-ki-tai-khoan",
  PasswordForgot: "/quen-mat-khau",
  AdminHome: "/trang-chu-admin",
  ManagerHome: "/trang-chu-manager",
  UnAuthorization: "/khong-co-quyen-truy-cap",
  UserList: "/danh-sach-nguoi-dung",
  AddUser: "/them-nguoi-dung",
  AddMovie: "/them-phim",
  MovieList: "/danh-sach-phim",
  Movie: "/movie",
  AddMovieSession: "/them-suat-chieu-phim",
  Booking: "/dat-ve-xem-phim",
  ServiceBook: "/dat-do-an",
  BookConfirm: "/xac-nhan",
};

export default routes;
